spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  liquibase:
    change-log: database/changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  messages:
    basename: localization/messages